require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssayFilesController do

  # This should return the minimal set of attributes required to create a valid
  # AssayFile. As you add validations to AssayFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all assay_files as @assay_files" do
      assay_file = AssayFile.create! valid_attributes
      get :index
      assigns(:assay_files).should eq([assay_file])
    end
  end

  describe "GET show" do
    it "assigns the requested assay_file as @assay_file" do
      assay_file = AssayFile.create! valid_attributes
      get :show, :id => assay_file.id.to_s
      assigns(:assay_file).should eq(assay_file)
    end
  end

  describe "GET new" do
    it "assigns a new assay_file as @assay_file" do
      get :new
      assigns(:assay_file).should be_a_new(AssayFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested assay_file as @assay_file" do
      assay_file = AssayFile.create! valid_attributes
      get :edit, :id => assay_file.id.to_s
      assigns(:assay_file).should eq(assay_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssayFile" do
        expect {
          post :create, :assay_file => valid_attributes
        }.to change(AssayFile, :count).by(1)
      end

      it "assigns a newly created assay_file as @assay_file" do
        post :create, :assay_file => valid_attributes
        assigns(:assay_file).should be_a(AssayFile)
        assigns(:assay_file).should be_persisted
      end

      it "redirects to the created assay_file" do
        post :create, :assay_file => valid_attributes
        response.should redirect_to(AssayFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assay_file as @assay_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssayFile.any_instance.stub(:save).and_return(false)
        post :create, :assay_file => {}
        assigns(:assay_file).should be_a_new(AssayFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssayFile.any_instance.stub(:save).and_return(false)
        post :create, :assay_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assay_file" do
        assay_file = AssayFile.create! valid_attributes
        # Assuming there are no other assay_files in the database, this
        # specifies that the AssayFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssayFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => assay_file.id, :assay_file => {'these' => 'params'}
      end

      it "assigns the requested assay_file as @assay_file" do
        assay_file = AssayFile.create! valid_attributes
        put :update, :id => assay_file.id, :assay_file => valid_attributes
        assigns(:assay_file).should eq(assay_file)
      end

      it "redirects to the assay_file" do
        assay_file = AssayFile.create! valid_attributes
        put :update, :id => assay_file.id, :assay_file => valid_attributes
        response.should redirect_to(assay_file)
      end
    end

    describe "with invalid params" do
      it "assigns the assay_file as @assay_file" do
        assay_file = AssayFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssayFile.any_instance.stub(:save).and_return(false)
        put :update, :id => assay_file.id.to_s, :assay_file => {}
        assigns(:assay_file).should eq(assay_file)
      end

      it "re-renders the 'edit' template" do
        assay_file = AssayFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssayFile.any_instance.stub(:save).and_return(false)
        put :update, :id => assay_file.id.to_s, :assay_file => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assay_file" do
      assay_file = AssayFile.create! valid_attributes
      expect {
        delete :destroy, :id => assay_file.id.to_s
      }.to change(AssayFile, :count).by(-1)
    end

    it "redirects to the assay_files list" do
      assay_file = AssayFile.create! valid_attributes
      delete :destroy, :id => assay_file.id.to_s
      response.should redirect_to(assay_files_url)
    end
  end

end
