require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssemblyFilesController do

  # This should return the minimal set of attributes required to create a valid
  # AssemblyFile. As you add validations to AssemblyFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all assembly_files as @assembly_files" do
      assembly_file = AssemblyFile.create! valid_attributes
      get :index
      assigns(:assembly_files).should eq([assembly_file])
    end
  end

  describe "GET show" do
    it "assigns the requested assembly_file as @assembly_file" do
      assembly_file = AssemblyFile.create! valid_attributes
      get :show, :id => assembly_file.id.to_s
      assigns(:assembly_file).should eq(assembly_file)
    end
  end

  describe "GET new" do
    it "assigns a new assembly_file as @assembly_file" do
      get :new
      assigns(:assembly_file).should be_a_new(AssemblyFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested assembly_file as @assembly_file" do
      assembly_file = AssemblyFile.create! valid_attributes
      get :edit, :id => assembly_file.id.to_s
      assigns(:assembly_file).should eq(assembly_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssemblyFile" do
        expect {
          post :create, :assembly_file => valid_attributes
        }.to change(AssemblyFile, :count).by(1)
      end

      it "assigns a newly created assembly_file as @assembly_file" do
        post :create, :assembly_file => valid_attributes
        assigns(:assembly_file).should be_a(AssemblyFile)
        assigns(:assembly_file).should be_persisted
      end

      it "redirects to the created assembly_file" do
        post :create, :assembly_file => valid_attributes
        response.should redirect_to(AssemblyFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assembly_file as @assembly_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyFile.any_instance.stub(:save).and_return(false)
        post :create, :assembly_file => {}
        assigns(:assembly_file).should be_a_new(AssemblyFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyFile.any_instance.stub(:save).and_return(false)
        post :create, :assembly_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assembly_file" do
        assembly_file = AssemblyFile.create! valid_attributes
        # Assuming there are no other assembly_files in the database, this
        # specifies that the AssemblyFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssemblyFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => assembly_file.id, :assembly_file => {'these' => 'params'}
      end

      it "assigns the requested assembly_file as @assembly_file" do
        assembly_file = AssemblyFile.create! valid_attributes
        put :update, :id => assembly_file.id, :assembly_file => valid_attributes
        assigns(:assembly_file).should eq(assembly_file)
      end

      it "redirects to the assembly_file" do
        assembly_file = AssemblyFile.create! valid_attributes
        put :update, :id => assembly_file.id, :assembly_file => valid_attributes
        response.should redirect_to(assembly_file)
      end
    end

    describe "with invalid params" do
      it "assigns the assembly_file as @assembly_file" do
        assembly_file = AssemblyFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyFile.any_instance.stub(:save).and_return(false)
        put :update, :id => assembly_file.id.to_s, :assembly_file => {}
        assigns(:assembly_file).should eq(assembly_file)
      end

      it "re-renders the 'edit' template" do
        assembly_file = AssemblyFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyFile.any_instance.stub(:save).and_return(false)
        put :update, :id => assembly_file.id.to_s, :assembly_file => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assembly_file" do
      assembly_file = AssemblyFile.create! valid_attributes
      expect {
        delete :destroy, :id => assembly_file.id.to_s
      }.to change(AssemblyFile, :count).by(-1)
    end

    it "redirects to the assembly_files list" do
      assembly_file = AssemblyFile.create! valid_attributes
      delete :destroy, :id => assembly_file.id.to_s
      response.should redirect_to(assembly_files_url)
    end
  end

end
