require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FileTypesController do

  # This should return the minimal set of attributes required to create a valid
  # FileType. As you add validations to FileType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all file_types as @file_types" do
      file_type = FileType.create! valid_attributes
      get :index
      assigns(:file_types).should eq([file_type])
    end
  end

  describe "GET show" do
    it "assigns the requested file_type as @file_type" do
      file_type = FileType.create! valid_attributes
      get :show, :id => file_type.id.to_s
      assigns(:file_type).should eq(file_type)
    end
  end

  describe "GET new" do
    it "assigns a new file_type as @file_type" do
      get :new
      assigns(:file_type).should be_a_new(FileType)
    end
  end

  describe "GET edit" do
    it "assigns the requested file_type as @file_type" do
      file_type = FileType.create! valid_attributes
      get :edit, :id => file_type.id.to_s
      assigns(:file_type).should eq(file_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FileType" do
        expect {
          post :create, :file_type => valid_attributes
        }.to change(FileType, :count).by(1)
      end

      it "assigns a newly created file_type as @file_type" do
        post :create, :file_type => valid_attributes
        assigns(:file_type).should be_a(FileType)
        assigns(:file_type).should be_persisted
      end

      it "redirects to the created file_type" do
        post :create, :file_type => valid_attributes
        response.should redirect_to(FileType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved file_type as @file_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileType.any_instance.stub(:save).and_return(false)
        post :create, :file_type => {}
        assigns(:file_type).should be_a_new(FileType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileType.any_instance.stub(:save).and_return(false)
        post :create, :file_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested file_type" do
        file_type = FileType.create! valid_attributes
        # Assuming there are no other file_types in the database, this
        # specifies that the FileType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FileType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => file_type.id, :file_type => {'these' => 'params'}
      end

      it "assigns the requested file_type as @file_type" do
        file_type = FileType.create! valid_attributes
        put :update, :id => file_type.id, :file_type => valid_attributes
        assigns(:file_type).should eq(file_type)
      end

      it "redirects to the file_type" do
        file_type = FileType.create! valid_attributes
        put :update, :id => file_type.id, :file_type => valid_attributes
        response.should redirect_to(file_type)
      end
    end

    describe "with invalid params" do
      it "assigns the file_type as @file_type" do
        file_type = FileType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileType.any_instance.stub(:save).and_return(false)
        put :update, :id => file_type.id.to_s, :file_type => {}
        assigns(:file_type).should eq(file_type)
      end

      it "re-renders the 'edit' template" do
        file_type = FileType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileType.any_instance.stub(:save).and_return(false)
        put :update, :id => file_type.id.to_s, :file_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested file_type" do
      file_type = FileType.create! valid_attributes
      expect {
        delete :destroy, :id => file_type.id.to_s
      }.to change(FileType, :count).by(-1)
    end

    it "redirects to the file_types list" do
      file_type = FileType.create! valid_attributes
      delete :destroy, :id => file_type.id.to_s
      response.should redirect_to(file_types_url)
    end
  end

end
