require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GenomeReferencesController do

  # This should return the minimal set of attributes required to create a valid
  # GenomeReference. As you add validations to GenomeReference, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
    :name => "hg19"
    }
  end

  describe "GET index" do
    it "assigns all genome_references as @genome_references" do
      genome_reference = GenomeReference.create! valid_attributes
      get :index
      assigns(:genome_references).should eq([genome_reference])
    end
  end

  describe "GET show" do
    it "assigns the requested genome_reference as @genome_reference" do
      genome_reference = GenomeReference.create! valid_attributes
      get :show, :id => genome_reference.id.to_s
      assigns(:genome_reference).should eq(genome_reference)
    end
  end

  describe "GET new" do
    it "assigns a new genome_reference as @genome_reference" do
      get :new
      assigns(:genome_reference).should be_a_new(GenomeReference)
    end
  end

  describe "GET edit" do
    it "assigns the requested genome_reference as @genome_reference" do
      genome_reference = GenomeReference.create! valid_attributes
      get :edit, :id => genome_reference.id.to_s
      assigns(:genome_reference).should eq(genome_reference)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GenomeReference" do
        expect {
          post :create, :genome_reference => valid_attributes
        }.to change(GenomeReference, :count).by(1)
      end

      it "assigns a newly created genome_reference as @genome_reference" do
        post :create, :genome_reference => valid_attributes
        assigns(:genome_reference).should be_a(GenomeReference)
        assigns(:genome_reference).should be_persisted
      end

      it "redirects to the created genome_reference" do
        post :create, :genome_reference => valid_attributes
        response.should redirect_to(GenomeReference.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved genome_reference as @genome_reference" do
        # Trigger the behavior that occurs when invalid params are submitted
        GenomeReference.any_instance.stub(:save).and_return(false)
        post :create, :genome_reference => {}
        assigns(:genome_reference).should be_a_new(GenomeReference)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GenomeReference.any_instance.stub(:save).and_return(false)
        post :create, :genome_reference => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested genome_reference" do
        genome_reference = GenomeReference.create! valid_attributes
        # Assuming there are no other genome_references in the database, this
        # specifies that the GenomeReference created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GenomeReference.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => genome_reference.id, :genome_reference => {'these' => 'params'}
      end

      it "assigns the requested genome_reference as @genome_reference" do
        genome_reference = GenomeReference.create! valid_attributes
        put :update, :id => genome_reference.id, :genome_reference => valid_attributes
        assigns(:genome_reference).should eq(genome_reference)
      end

      it "redirects to the genome_reference" do
        genome_reference = GenomeReference.create! valid_attributes
        put :update, :id => genome_reference.id, :genome_reference => valid_attributes
        response.should redirect_to(genome_reference)
      end
    end

    describe "with invalid params" do
      it "assigns the genome_reference as @genome_reference" do
        genome_reference = GenomeReference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GenomeReference.any_instance.stub(:save).and_return(false)
        put :update, :id => genome_reference.id.to_s, :genome_reference => {}
        assigns(:genome_reference).should eq(genome_reference)
      end

      it "re-renders the 'edit' template" do
        genome_reference = GenomeReference.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GenomeReference.any_instance.stub(:save).and_return(false)
        put :update, :id => genome_reference.id.to_s, :genome_reference => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested genome_reference" do
      genome_reference = GenomeReference.create! valid_attributes
      expect {
        delete :destroy, :id => genome_reference.id.to_s
      }.to change(GenomeReference, :count).by(-1)
    end

    it "redirects to the genome_references list" do
      genome_reference = GenomeReference.create! valid_attributes
      delete :destroy, :id => genome_reference.id.to_s
      response.should redirect_to(genome_references_url)
    end
  end

end
