require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PedigreesController do

  describe "associations" do
    subject { build(:pedigree) }

    it { should have_many(:people) }
    it { should have_many(:memberships) }
    it { should belong_to(:study) }
  end

  describe "validations" do
    subject { build(:pedigree) }
    
    it { should validate_presence_of(:name) }
    it { should validate_presence_of(:tag) }
    it { should validate_presence_of(:study_id) }

    it { should validate_uniqueness_of(:name) }
    it { should validate_uniqueness_of(:tag) }
  end

  describe "GET index" do
    it "assigns all pedigrees as @pedigrees" do
      pedigree = create(:pedigree)
      get :index
      assigns(:pedigrees).should eq([pedigree])
    end
  end

  describe "GET show" do
    it "assigns the requested pedigree as @pedigree" do
      pedigree = create(:pedigree)
      get :show, :id => pedigree.id.to_s
      assigns(:pedigree).should eq(pedigree)
    end
  end

  describe "GET new" do
    it "assigns a new pedigree as @pedigree" do
      get :new
      assigns(:pedigree).should be_a_new(Pedigree)
    end
  end

  describe "GET edit" do
    it "assigns the requested pedigree as @pedigree" do
      pedigree = create(:pedigree)
      get :edit, :id => pedigree.id.to_s
      assigns(:pedigree).should eq(pedigree)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pedigree" do
        expect {
          post :create, :pedigree => build(:pedigree).attributes
        }.to change(Pedigree, :count).by(1)
      end

      it "assigns a newly created pedigree as @pedigree" do
        post :create, :pedigree => build(:pedigree).attributes
        assigns(:pedigree).should be_a(Pedigree)
        assigns(:pedigree).should be_persisted
      end

      it "redirects to the created pedigree" do
        post :create, :pedigree => build(:pedigree).attributes
        response.should redirect_to(Pedigree.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pedigree as @pedigree" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pedigree.any_instance.stub(:save).and_return(false)
        post :create, :pedigree => { :name => nil }
        assigns(:pedigree).should be_a_new(Pedigree)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pedigree.any_instance.stub(:save).and_return(false)
        post :create, :pedigree => { :name => nil }
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pedigree" do
        pedigree = create(:pedigree)
        # Assuming there are no other pedigrees in the database, this
        # specifies that the Pedigree created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pedigree.any_instance.should_receive(:update_attributes).with({'name' => 'test'})
        put :update, :id => pedigree.id, :pedigree => {'name' => 'test'}
      end

      it "assigns the requested pedigree as @pedigree" do
        pedigree = create(:pedigree)
        put :update, :id => pedigree.id, :pedigree => build(:pedigree).attributes
        assigns(:pedigree).should eq(pedigree)
      end

      it "redirects to the pedigree" do
        pedigree = create(:pedigree)
        put :update, :id => pedigree.id, :pedigree => build(:pedigree).attributes
        response.should redirect_to(pedigree)
      end
    end

    describe "with invalid params" do
      it "assigns the pedigree as @pedigree" do
        pedigree = create(:pedigree)
        # Trigger the behavior that occurs when invalid params are submitted
        Pedigree.any_instance.stub(:save).and_return(false)
        put :update, :id => pedigree.id.to_s, :pedigree => {}
        assigns(:pedigree).should eq(pedigree)
      end

      it "re-renders the 'edit' template" do
        pedigree = create(:pedigree)
        # Trigger the behavior that occurs when invalid params are submitted
        Pedigree.any_instance.stub(:save).and_return(false)
        put :update, :id => pedigree.id.to_s, :pedigree => {}
        #response.should render_template("edit")
        response.should raise_error StandardError
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pedigree" do
      pedigree = create(:pedigree)
      expect {
        delete :destroy, :id => pedigree.id.to_s
      }.to change(Pedigree, :count).by(-1)
    end

    it "redirects to the pedigrees list" do
      pedigree = create(:pedigree)
      delete :destroy, :id => pedigree.id.to_s
      response.should redirect_to(pedigrees_url)
    end
  end

end
