require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SampleAssaysController do

  # This should return the minimal set of attributes required to create a valid
  # SampleAssay. As you add validations to SampleAssay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sample_assays as @sample_assays" do
      sample_assay = SampleAssay.create! valid_attributes
      get :index
      assigns(:sample_assays).should eq([sample_assay])
    end
  end

  describe "GET show" do
    it "assigns the requested sample_assay as @sample_assay" do
      sample_assay = SampleAssay.create! valid_attributes
      get :show, :id => sample_assay.id.to_s
      assigns(:sample_assay).should eq(sample_assay)
    end
  end

  describe "GET new" do
    it "assigns a new sample_assay as @sample_assay" do
      get :new
      assigns(:sample_assay).should be_a_new(SampleAssay)
    end
  end

  describe "GET edit" do
    it "assigns the requested sample_assay as @sample_assay" do
      sample_assay = SampleAssay.create! valid_attributes
      get :edit, :id => sample_assay.id.to_s
      assigns(:sample_assay).should eq(sample_assay)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SampleAssay" do
        expect {
          post :create, :sample_assay => valid_attributes
        }.to change(SampleAssay, :count).by(1)
      end

      it "assigns a newly created sample_assay as @sample_assay" do
        post :create, :sample_assay => valid_attributes
        assigns(:sample_assay).should be_a(SampleAssay)
        assigns(:sample_assay).should be_persisted
      end

      it "redirects to the created sample_assay" do
        post :create, :sample_assay => valid_attributes
        response.should redirect_to(SampleAssay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sample_assay as @sample_assay" do
        # Trigger the behavior that occurs when invalid params are submitted
        SampleAssay.any_instance.stub(:save).and_return(false)
        post :create, :sample_assay => {}
        assigns(:sample_assay).should be_a_new(SampleAssay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SampleAssay.any_instance.stub(:save).and_return(false)
        post :create, :sample_assay => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sample_assay" do
        sample_assay = SampleAssay.create! valid_attributes
        # Assuming there are no other sample_assays in the database, this
        # specifies that the SampleAssay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SampleAssay.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sample_assay.id, :sample_assay => {'these' => 'params'}
      end

      it "assigns the requested sample_assay as @sample_assay" do
        sample_assay = SampleAssay.create! valid_attributes
        put :update, :id => sample_assay.id, :sample_assay => valid_attributes
        assigns(:sample_assay).should eq(sample_assay)
      end

      it "redirects to the sample_assay" do
        sample_assay = SampleAssay.create! valid_attributes
        put :update, :id => sample_assay.id, :sample_assay => valid_attributes
        response.should redirect_to(sample_assay)
      end
    end

    describe "with invalid params" do
      it "assigns the sample_assay as @sample_assay" do
        sample_assay = SampleAssay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SampleAssay.any_instance.stub(:save).and_return(false)
        put :update, :id => sample_assay.id.to_s, :sample_assay => {}
        assigns(:sample_assay).should eq(sample_assay)
      end

      it "re-renders the 'edit' template" do
        sample_assay = SampleAssay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SampleAssay.any_instance.stub(:save).and_return(false)
        put :update, :id => sample_assay.id.to_s, :sample_assay => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sample_assay" do
      sample_assay = SampleAssay.create! valid_attributes
      expect {
        delete :destroy, :id => sample_assay.id.to_s
      }.to change(SampleAssay, :count).by(-1)
    end

    it "redirects to the sample_assays list" do
      sample_assay = SampleAssay.create! valid_attributes
      delete :destroy, :id => sample_assay.id.to_s
      response.should redirect_to(sample_assays_url)
    end
  end

end
